# Generated by Django 4.0.6 on 2022-08-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasYRespuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuestaCorrecta', models.CharField(max_length=255)),
                ('respuestaIncorrecta1', models.CharField(max_length=255)),
                ('respuestaIncorrecta2', models.CharField(max_length=255)),
                ('respuestaIncorrecta3', models.CharField(max_length=255)),
                ('usada', models.BooleanField(default=False)),
            ],
        ),
    ]
