# Generated by Django 4.0.6 on 2022-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_de_Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasyrespuestas',
            name='genero',
            field=models.CharField(default='Historia', max_length=255),
        ),
    ]
