# Generated by Django 4.0.6 on 2022-08-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='preguntasAcertadas',
            field=models.IntegerField(default=0),
        ),
    ]
