# Generated by Django 4.0.6 on 2022-08-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0003_alter_usuario_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tiempo',
            field=models.CharField(default='00m 00s', max_length=30),
        ),
    ]
