# Generated by Django 4.0.6 on 2022-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0005_alter_usuario_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='posicion',
            field=models.IntegerField(default=0),
        ),
    ]
