# Generated by Django 4.0.6 on 2022-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0006_usuario_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='generoElegido',
            field=models.CharField(default='Predeterminado', max_length=10),
        ),
    ]
