# Generated by Django 4.0.6 on 2022-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0007_usuario_generoelegido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='generoElegido',
            field=models.CharField(default='Historia', max_length=10),
        ),
    ]
